-- INSERT INTO users (username, email, password) 
-- VALUES
--     ('Ismael', 'someone@gman.com', 'pass'),
--     ('Daiana', 'someone@gone.com', 'password'),
--     ('Taro', 'someone@tone.com', 'qwerty'),
--     ('Reece', 'someone@tnone.come', '123qwe')